git ls-files | xargs -n 1 sed -i '' \
	-e 's/anIdentity/identity:/g' \
	-e 's/aConst/const:/g' \
	-e 's/aFirst/first:/g' \
	-e 's/aLast/last:/g' \
	-e 's/anAny/any:/g' \
	-e 's/anAll/all:/g' \
	-e 's/aSum/sum:/g' \
	-e 's/aProduct/product:/g' \
	-e 's/aDual/dual:/g' \
	-e 's/anEndo/endo:/g' \
	-e 's/aMax/max:/g' \
	-e 's/aMin/min:/g' \
	-e 's/aReaderT/readerT:/g' \
	-e 's/aWriterT/writerT:/g' \
	-e 's/aStateT/stateT:/g' \
	-e 's/aStateR/stateR:/g' \
	-e 's/aStateL/stateL:/g' \
	-e 's/aContT/contT:/g' \
	-e 's/aReader/reader:/g' \
	-e 's/aWriter/writer:/g' \
	-e 's/aCont/cont:/g'
