module Data.Functor.Coyoneda where

open import Prelude

private
  variable
    a b : Set
    f g : Set -> Set

-- This is the existensial version Yoneda F A.
data Coyoneda (f : Set -> Set) (b : Set) : Set where
  toCoyoneda : f a -> (a -> b) -> Coyoneda f b

-- Coyoneda C F is a functor.
instance
  functorCoyoneda : Functor (Coyoneda f)
  functorCoyoneda .map f (toCoyoneda x g) = toCoyoneda x (f ∘ g)

-- The coYoneda lemma states that F B ~= Coyoneda C F Y. The isomorphsim
-- is witnessed by lower and lift.
lower : {{_ : Functor f}} -> Coyoneda f a -> f a
lower (toCoyoneda x f) = map f x

lift : f a -> Coyoneda f a
lift y = toCoyoneda y id

-- It turns out that Coyoneda is a free construction, i.e. Coyoneda C F is
-- the free functor generated by F. This is the right adjunct of the
-- corresponding free/forgetful adjunction.
interpret : {{_ : Functor g}} -> (f ~> g) -> Coyoneda f ~> g
interpret t (toCoyoneda x f) = map f (t x)

-- This is the left adjunct.
uninterpret :  (Coyoneda f ~> g) -> f ~> g
uninterpret t x = t (lift x)
